/**
 * build-single.mjs — bundles the modular source into one offline HTML file.
 *
 * Why this exists: ES modules cannot be loaded from file:// (module fetches are
 * subject to CORS and file:// origins are opaque), and the codebase must stay
 * framework-free with a zero-build workflow. So the modular files remain the
 * source of truth and this script emits a single-file artifact for offline or
 * sandboxed viewing. Run: node build-single.mjs > ink-layer-preview.html
 */
import { readFileSync } from 'node:fs';

const dir = new URL('./', import.meta.url);
const read = (f) => readFileSync(new URL(f, dir), 'utf8');

const css = read('ink-layer.css') + '\n' + read('detent.css');
const core = read('core.js');
const layer = read('ink-layer.js');

/* Collect core.js's exported names so the merged scope can expose the same
   namespace the wiring layer expects (C.*). */
const names = [];
for (const m of core.matchAll(/^export\s+(?:const|function|class|let)\s+([A-Za-z_$][\w$]*)/gm)) names.push(m[1]);
if (!names.length) throw new Error('no exports found in core.js');
const dupes = names.filter((n, i) => names.indexOf(n) !== i);
if (dupes.length) throw new Error('duplicate exports: ' + dupes.join(', '));

/* Verification 1: core.js must not declare a non-exported top-level binding
   that the wiring layer also declares — flattening modules into one scope turns
   that into a SyntaxError, not a shadowing. */
const wiringNames = [...layer.matchAll(/^(?:const|let|function|class)\s+([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]);
const coreAllNames = [...core.matchAll(/^(?:export\s+)?(?:const|let|function|class)\s+([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]);
const clash = wiringNames.filter((n) => coreAllNames.includes(n));
if (clash.length) throw new Error('name collision between core.js and ink-layer.js: ' + clash.join(', '));

/* Verification 2: every property the wiring layer reads off C.* must exist. */
const used = new Set([...layer.matchAll(/\bC\.([A-Za-z_$][\w$]*)/g)].map((m) => m[1]));
const missing = [...used].filter((u) => !names.includes(u));
if (missing.length) throw new Error('ink-layer.js reads C.' + missing.join(', C.') + ' which core.js does not export');

/* Verification 3: exactly one import statement, and it is the core namespace. */
const importLines = layer.match(/^\s*import .*$/gm) || [];
if (importLines.length !== 1 || !/from '\.\/core\.js'/.test(importLines[0])) {
  throw new Error('expected exactly one `import ... from \'./core.js\'`, found: ' + JSON.stringify(importLines));
}

const strip = (src) => src.replace(/^export\s+(?=(?:const|let|function|class))/gm, '');
const layerBody = layer.replace(/^\s*import .*$/m, '');
const ns = `const C = Object.freeze({ ${names.join(', ')} });\n`;
/* ORDER IS LOAD-BEARING: the namespace object REFERENCES the core bindings, so
   it must be evaluated after them (a const read before its declaration is a
   TDZ ReferenceError, not undefined) and before the wiring layer that consumes
   it. Emitting the namespace first — the obvious order — produces a bundle that
   throws "Cannot access 'DWELL_MS' before initialization" and renders nothing. */
const body = strip(core) + '\n' + ns + '\n' + layerBody;

const html = `<!doctype html>
<html lang="en" data-ground="instrument">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Ink Layer — single-file build</title>
<!-- GENERATED by build-single.mjs from core.js + ink-layer.js + ink-layer.css + detent.css.
     The two stylesheets are inlined in cascade order: structure first, then the
     colour pass that paints it.
     Do not edit: edit the sources and re-run the bundler.
     This build talks to nothing: with no local studio answering /api/health it
     runs the demo craft adapter, so every mechanism is exercisable offline. -->
<style>
${css}
</style>
</head>
<body>
  <main class="surface" id="surface">
    <article class="manuscript" id="manuscript" role="document" aria-label="Screenplay manuscript" aria-busy="true"></article>
  </main>
  <div class="horizon" id="horizon" role="slider" tabindex="0" aria-orientation="vertical"
       aria-label="Document horizon: scene proportion, ink, and viewport position"
       aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" aria-valuetext="Top of script">
    <svg class="hz-track" id="hzTrack" preserveAspectRatio="none" aria-hidden="true" focusable="false">
      <g id="hzBands"></g><g id="hzInk"></g>
      <rect id="hzWindow" class="hz-window" x="0" width="100%" height="0"></rect>
    </svg>
  </div>
  <p class="annunciator" id="annunciator" role="status" aria-live="polite" aria-atomic="true"></p>
  <noscript><p style="padding:2rem">The Ink Layer needs scripting enabled.</p></noscript>
<script type="module">
${body}
</script>
</body>
</html>
`;
process.stdout.write(html);
